package pattern.detection;

public enum PATTERN_TYPE {
	SINGLETON,
	DECORATOR_COMPONENT,
	DECORATOR_CONCRETE,
	DECORATOR_DECORATOR,
	ADAPTER_ADAPTER,
	ADAPTER_ADAPTEE,
	ADAPTER_TARGET,
	COMPOSITE_COMPONENT,
	COMPOSITE_COMPOSITE,
	COMPOSITE_LEAF
}
